### PR TITLE
Add support for Solarman Smart Meter DTSD422-D3 and signed magnitude integer values.

### LINKED ISSUE #451: Solarman DTSD422-D3 Meter Logger
Hi,

I am trying to integrate the Solarman DTSD422-D3 Meter logger
FW: LSW3_15_E02D_1.05

It should show something i think with sofar_lsw3.yaml, since the "requests" and "registers" should be almost the same.
But no luck for me, "Unknown" and "Disconnected")

Has anyone any ideas or gotten it to work?

I have 
2p Sofar KTLX-G3 24kw, with LSW-3 wifi dongle, Smart meter at Grid (Currently working "zcs_azzurro-ktl-v3.yaml")
4p DTSD422-D3 (testing with sofar_lsw3.yaml)

FYI I am using the DTSD422-D3 Meters for some separate load measurements that i wanna show in HA

DTSD422-D3:
https://www.solarmanpv.com/products/smart-meter/

Modbus protocol that i prob could use to custimize a .yaml if i could atleast get them connected:
https://github.com/kbialek/deye-inverter-mqtt/blob/main/docs/metric_group_igen_dtsd422.md

### PR DESCRIPTION
**Pull request by Triple-S**
Hello,

This commit adds support for Solarman Smart Meter DTSD422-D3. Since this device uses signed magnitude integer values I also had to add a parser for them.

I tested everything with my Home Assistant ant it seemed to work perfectly fine. For the moment I added all values besides the integrated energy values because the binary output shows a lot of values I cannot allocate to any meaningful information which is why I ommited them to not add some wrong information.

This PR fixes #451 and #520.

IMPORTANT QUESTION: I realized that the original signed integer parser is written for one's complement signed integers which I find astonishing since usually two's complement signed integers are used. Was this confirmed that Solarman devices actually use one's complement signed integers? Otherwise all negative values have an offset of -1.

### CODE REVIEW

**Comment by bobybob69** [comment]
hi @Triple-S and thanks for your work integrating smart meter from solarman. 
I have the D2 but it should work the same as D3 no ? Also, how can I add your commit to my HA setup ? I'm not familiar with this part of the coding process, so If you could help that would be nice :) 
I'm running HA on a RPi , it's the HA image from raspberry pi imager. 
Thanks in advance for your time and your support !

**Comment by Triple-S** [comment]
Hi @bobybob69,
I don't know whether it works with the D2 as I don't have one and thereby cannot verify the register addesses. Concerning adding the commit to your setup you should wait until it gets merged into the official repository if you don't know how to do the merging manually. I proposed this addition 4 months ago and still did not received a single response from the maintainers, so it might take a while if it even gets merged at all. In the meanwhile some changes to the repository have been made that are incompatible with my changes, so some manual actions are required, but I will not do this until I get a response from the maintainers.
Best regards.

**Comment by bobybob69** [comment]
Hi @Triple-S thanks for your answer ! I tried few steps doing the integration manually from the file editor menu. I just added your commit and not the other from now. 
I'm should not be so far from the right things as I copy/past the files you've change into the actual setup. The only thing is I don't have the smart meter listing when I have to choose parameters (cf screenshot). Perhaps I miss something when doing the manual integration ? 
What I did is from the file editor : 
- create custom_components/solarman/inverter_definitions/solarman_dtsd422-d3.yaml and paste your code 
- paste your new code for "parser.py" 

there is just the readme.md file and the customization.md I don't have on the folder from the file editor on my HA setup. 

What's your thought about the manual integration ? Any miss I could made to not having the parameters listed in the menu ? 

I'll try to message the owner also .. perhaps if he get multiple notifications he will do something..? 

Thanks you ! 

Capture d’écran 2024-08-14 à 09 41 04

**Comment by bobybob69** [comment]
Hi @Triple-S , hope you’re fine ? 
Did you get answer from @StephanJoubert about your integration ? 
everything looks to be ready to implement so I hope it will be integrate soon into the main branch 
Thanks for your work , can’t wait to have it live !

**Comment by frsantos** [comment]
Hey,

Just passing by to tell you about the new Solarman integration in https://github.com/davidrapan/ha-solarman, spawned from this one. It's very well maintained and his developer is very quick on support. It probably needs a rename of the entities on installation, but apart from that it's a sure win.

**Comment by bobybob69** [comment]
hey @frsantos thanks for sharing this ! 
just installed it on my HA install :) 
However, the D2 is still not working with this integration, only the D3 is set apparently.. Just submitted a pull request (almost the same as this one) . if you know something about D2 integration feel free to share in the https://github.com/davidrapan/ha-solarman/issues/188 ,  thanks again for taking a look here and share the new integration :)

**Comment by Triple-S** [comment]
Closed because nobody cares

**Comment by PV-Joe** [comment]
The device is supported by this integration:

https://github.com/davidrapan/ha-solarman

**Comment by bobybob69** [comment]
Hi @PV-Joe , unfortunately I'm looking for the DDZY422-D2 to be integrated, any help would be helpful to be honest. 

I've open an issue here : https://github.com/davidrapan/ha-solarman/issues/187 

But I'm challenged with the modbus register as solarman don't have it (or they don't want to share it) 

thanks in advance :)

**Pull request closed without merging**
