### PR TITLE
Additions to deye_sg04lp3.yaml

### PR DESCRIPTION
**Pull request by mrboogiee**
several additional counters added in line with open requests from issue #88 and some additional parameters not yet requested in the issue.

### CODE REVIEW

**Comment by mrboogiee** [comment]
Closes #88

**Comment by Bingo2023** [comment]
can we merge this? I have tested it and it works great.
Only:
- Phase power of Gen port A
- Phase power of Gen port B
shows no value at my Inverter.

**Comment by mrboogiee** [comment]
@Bingo2023 which inverter did you test this with? Is your Gen port input delivering 3-phase power? I want to make sure that it's not something due to my proposed changes.

**Comment by Bingo2023** [comment]
I tested with "DEYE Sun 12K SG04LP3"
Gen Input Port is not connected at the moment in my setup.

I have just rechecked it, now it shows 0W for all 3 Gen Ports. So I guess a couple of reboots solved it :)
-- sorry for that --

**Pull request merged**
