### PR TITLE
Add Sofarsolar Wifikit inverter definition

### PR DESCRIPTION
**Pull request by benagricola**
Adds a new inverter definition to support inverters with the "wifikit"
embedded data logger, with serial numbers starting `804xxxxxx` and
potentially others.

NOTE: Generation Power on the ME3000-SP returns a "special" 
value, 65534 when no generation is occurring. This is problematic
because it means generation power statistics will be inaccurate
overnight unless this value is rejected.

I have another small code change which I can add another PR for which
allows to set a range of valid values and returns a default value if a field
is outside that range - this PR does _not_ contain the relevant changes
here but I haven't heard anything on the issue for that (#83).

Signed-off-by: Ben Agricola <ben+git@agrico.la>

### CODE REVIEW

**Comment by benagricola** [comment]
Just to add, there's at least one other user on Discord who has been using this for a week or so and says it's working well.

**Comment by s0x00c** [comment]
Hey Ben

I am using the yaml file you added to StephanJoubert repo, thanks for that, now my ME3000SP is being read from Home Assistant.
There is just one thing missing IMHO, would it be possible to provide the energy dashboard add-in entities or if you know them, the addresses that need to be read when those values are stored on the ME3000SP?
That would help a lot of people that are looking for this solution. (https://github.com/StephanJoubert/home_assistant_solarman/issues/114)

**Comment by benagricola** [comment]
Hi @s0x00c - the energy dashboard requires _energy consumption_ values rather than the instant power values that the ME3000SP supplies. As far as I'm aware there's no missing fields (I implemented all the fields from the datasheet that could be reasonably read with the `home_assistant_solarman` plugin).

I think what you're missing is an, honestly, poorly documented feature of the energy dashboard, which is that if your device doesn't already provide battery charge and discharge, grid usage and feed-in as values-over-time (KWh) then you need riemann sensors to generate these from the instant values.

Try adding these two sensors below. Note: the name of the fields (`sensor.home_...`) will depend on what you called the solarman integration itself.

```yaml
- sensor:
    - name: "Battery Charge Power"
      state_class: "measurement"
      device_class: "power"
      unit_of_measurement: "kW"
      icon: mdi:battery-plus
      state: >
        {% if states('sensor.home_battery_charge_discharge_power')|float >= 0 %}
          {{ states('sensor.home_battery_charge_discharge_power') }}
        {% else %}
          0
        {% endif %}
    - name: "Battery Discharge Power"
      state_class: "measurement"
      device_class: "power"
      unit_of_measurement: "kW"
      icon: mdi:battery-minus
      state: >
        {% if states('sensor.home_battery_charge_discharge_power')|float < 0 %}
          {{ -1 * states('sensor.home_battery_charge_discharge_power')|float }}
        {% else %}
          0
        {% endif %}
```

**Comment by meteosat007** [comment]
Thats funny I applied the same template sensors to mine on the Sofar HYD3-6.yaml
All energy functions working and I also added a Battery Status sensor below.

    - name: "Solarman Battery Status"
      unique_id: sensor.solarman_battery_status
      state: >
        {% if states('sensor.solarman_charge_discharge_power')|float < 0 %}
          discharging
        {% elif states('sensor.solarman_charge_discharge_power')|float > 0 %}
          charging
        {% else %}
          standby
        {% endif %}

**Comment by s0x00c** [comment]
@benagricola : wow, thanks for the quick reply and for the explanation:
I added the 2 new sensors as follows:
image
but in the logs I can find this:
TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{% if states('sensor.solarman_battery_charge_discharge_power')|float >= 0 %} {{ states('sensor.solarman_battery_charge_discharge_power') }} {% else %} 0 {% endif %}' but no default was specified') while processing template 'Template("{% if states('sensor.solarman_battery_charge_discharge_power')|float >= 0 %} {{ states('sensor.solarman_battery_charge_discharge_power') }} {% else %} 0 {% endif %}")' for attribute '_attr_native_value' in entity 'sensor.battery_charge_power'
09:35:09 – (ERROR) helpers/template_entity.py - message first occurred at 09:35:09 and shows up 2 times
Error while processing template: Template("{% if states('sensor.solarman_battery_charge_discharge_power')|float >= 0 %} {{ states('sensor.solarman_battery_charge_discharge_power') }} {% else %} 0 {% endif %}")
09:35:09 – (ERROR) helpers/template.py - message first occurred at 09:35:09 and shows up 2 times

**Comment by meteosat007** [comment]
I would double check that the sensor used in my templates are in your HA system. Should be if you have used the Sofar HYD3-6... yaml file.On 10 Jan 2023 08:55, s0x00c ***@***.***> wrote:
I've tried your version as well @meteosat007

but I get an error message:
First occurred: 09:53:35 (1 occurrences)
Last logged: 09:53:35
Invalid config for [template]: extra keys not allowed @ data['state']. Got "{% if states('sensor.solarman_charge_discharge_power')|float < 0 %}\n discharging\n{% elif states('sensor.solarman_charge_discharge_power')|float > 0 %}\n charging\n{% else %}\n standby\n{% endif %}\n" required key not provided @ data['sensor'][0]['state']. Got None. (See /config/configuration.yaml, line 16).

**Comment by s0x00c** [comment]
I did have the word 'battery' in the name of the sensor extra compared to yours, so I added that
image
so "sensor.solarman_battery_charge_discharge_power" is my name for the sensor, I changed the configuration.yaml to reflect that difference:
image
but it still gives me this error:
Full log:
2023-01-10 10:26:38.436 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{% if states('sensor.solarman_battery_charge_discharge_power')|float < 0 %}
discharging
{% elif states('sensor.solarman_battery_charge_discharge_power')|float > 0 %}
charging
{% else %}
standby
{% endif %}")
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1710, in forgiving_float_filter
return float(value)
ValueError: could not convert string to float: 'unknown'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 423, in async_render
render_result = _render_with_context(self.template, compiled, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1942, in _render_with_context
return template.render(**kwargs)
File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
raise rewrite_traceback_stack(source=source)
File "<template>", line 1, in top-level template code
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1713, in forgiving_float_filter
raise_no_default("float", value)
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1411, in raise_no_default
raise ValueError(
ValueError: Template error: float got invalid input 'unknown' when rendering template '{% if states('sensor.solarman_battery_charge_discharge_power')|float < 0 %}
discharging
{% elif states('sensor.solarman_battery_charge_discharge_power')|float > 0 %}
charging
{% else %}
standby
{% endif %}' but no default was specified
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 540, in async_render_to_info
render_info._result = self.async_render(variables, strict=strict, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 425, in async_render
raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{% if states('sensor.solarman_battery_charge_discharge_power')|float < 0 %}
discharging
{% elif states('sensor.solarman_battery_charge_discharge_power')|float > 0 %}
charging
{% else %}
standby
{% endif %}' but no default was specified
2023-01-10 10:26:38.438 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{% if states('sensor.solarman_battery_charge_discharge_power')|float < 0 %}
discharging
{% elif states('sensor.solarman_battery_charge_discharge_power')|float > 0 %}
charging
{% else %}
standby
{% endif %}' but no default was specified') while processing template 'Template("{% if states('sensor.solarman_battery_charge_discharge_power')|float < 0 %}
discharging
{% elif states('sensor.solarman_battery_charge_discharge_power')|float > 0 %}
charging
{% else %}
standby
{% endif %}")' for attribute '_attr_native_value' in entity 'sensor.solarman_battery_status'

**Comment by s0x00c** [comment]
I added default values and now HA doesn't complain anymore with the same errors:
```yaml
- sensor:
    - name: "Battery Charge Power"
      state_class: "measurement"
      device_class: "power"
      unit_of_measurement: "kW"
      icon: mdi:battery-plus
      state: >
        {% if states('sensor.home_battery_charge_discharge_power')|float(0) >= 0 %}
          {{ states('sensor.home_battery_charge_discharge_power') }}
        {% else %}
          0
        {% endif %}
    - name: "Battery Discharge Power"
      state_class: "measurement"
      device_class: "power"
      unit_of_measurement: "kW"
      icon: mdi:battery-minus
      state: >
        {% if states('sensor.home_battery_charge_discharge_power')|float(0) < 0 %}
          {{ -1 * states('sensor.home_battery_charge_discharge_power')|float(0) }}
        {% else %}
          0
        {% endif %}
```

But I don't know if I will get any values, it's night time now.

**Comment by s0x00c** [comment]
THis seems to be the correct code, for me at least.
Now, how to import it in the energy dashboard ?
```yaml
- sensor:
    - name: "Battery Charge Power"
      state_class: "measurement"
      device_class: "power"
      unit_of_measurement: "kW"
      icon: mdi:battery-plus
      state: >-
        {% set e = states('sensor.solarman_battery_charge_discharge_power') %}
        {{ e|float(0)|abs if e|float(0) >= 0 else 0 }}
      availability: >-
        {{ states('sensor.solarman_battery_charge_discharge_power')|is_number }}
    - name: "Battery Discharge Power"
      state_class: "measurement"
      device_class: "power"
      unit_of_measurement: "kW"
      icon: mdi:battery-minus
      state: >-
        {% set e = states('sensor.solarman_battery_charge_discharge_power') %}
        {{ e|float(0)|abs if e|float(0) <= 0 else 0 }}
      availability: >-
        {{ states('sensor.solarman_battery_charge_discharge_power')|is_number }}
```

**Comment by s0x00c** [comment]
So, eventually I found the solution:
We needed to split up the charge / discharge counter with a riemann calculation:

```
template:
  - sensor:
    - name: "Battery Charge Power"
      state_class: "measurement"
      device_class: "power"
      unit_of_measurement: "kW"
      icon: mdi:battery-plus
      state: >-
        {% set e = states('sensor.solarman_battery_charge_discharge_power') %}
        {{ e|float(0)|abs if e|float(0) >= 0 else 0 }}
      availability: >-
        {{ states('sensor.solarman_battery_charge_discharge_power')|is_number }}
    - name: "Battery Discharge Power"
      state_class: "measurement"
      device_class: "power"
      unit_of_measurement: "kW"
      icon: mdi:battery-minus
      state: >-
        {% set e = states('sensor.solarman_battery_charge_discharge_power') %}
        {{ e|float(0)|abs if e|float(0) <= 0 else 0 }}
      availability: >-
        {{ states('sensor.solarman_battery_charge_discharge_power')|is_number }}
```

and get that data then in the energy dashboard with adding this to the configuration.yaml file
```
sensor:
  - platform: integration
    source: sensor.battery_charge_power
    name: battery_charge_energy
    round: 2
  - platform: integration
    source: sensor.battery_discharge_power
    name: battery_discharge_energy
    round: 2
```

This gives you everything you need to get the data in the energy dashboard

**Comment by imellor** [comment]
@s0x00c   Thanks for this, I've been struggling to find away to integrate the battery in to the Energy Dashboard for a while. Having installed the custom component and applied the code above the battery is now showing in dashboard.
I have one glitch though, my battery starts an off-peak charge at 00:30 which is a 0 - 3kw jump. For some reason sensor_charge_energy increases the kwh every day at this point by approx 12kwh, which gives a incorrect graph on the energy dashboard.
Does you HA show this behaviour?

**Comment by s0x00c** [comment]
> @s0x00c Thanks for this, I've been struggling to find away to integrate the battery in to the Energy Dashboard for a while. Having installed the custom component and applied the code above the battery is now showing in dashboard. I have one glitch though, my battery starts an off-peak charge at 00:30 which is a 0 - 3kw jump. For some reason sensor_charge_energy increases the kwh every day at this point by approx 12kwh, which gives a incorrect graph on the energy dashboard. Does you HA show this behaviour?
> 
> I maybe answering my own question, I've just found this [thread](https://community.home-assistant.io/t/riemann-integral-calculates-wrong-values-with-electrical-devices/328174/2) I've amended "Method" to be "left", I'll report back what happens tomorrow morning.

I have not seen this behavior in my setup.

**Comment by imellor** [comment]
Changing "Method" to "Left" fixed it for me.
I could see what is was doing. It has been cloudy all week here, so the batteries charged a little at noon and than again at 00:30 
It was calculating the 3 kw jump in charge across the 12 hours to male 12kwh. Although not sure about the actual maths there :-)

**Pull request merged**
