### PR TITLE
fix: Fixed validation. Use a sequence number. Issue #268

### PR DESCRIPTION
**Pull request by charles-sd**
New validation added to prevent race condition: 
- generation of a sequence number
- sending sequence number in the echo field or requests 
- validating that the expected sequence number is found in responses before parsing the data 

Any mismatched responses are ignored. They are likely old responses received too late and the application state cannot deal with them.

Additional validation added:
- ensure that the response is of the expected length before parsing

### CODE REVIEW

**Comment by charles-sd** [comment]
Resolves #268

**Comment by jmccrohan** [comment]
@charles-sd [a8ecbd6](https://github.com/StephanJoubert/home_assistant_solarman/pull/270/commits/a8ecbd6f2632f602bdeb5d379cda611d0813ec43) looks *very* [familiar](https://github.com/jmccrohan/pysolarmanv5/commit/edeee309191cedb4b16437b66a852276740e6594). If you're going to copy code from [pysolarmanv5](https://github.com/jmccrohan/pysolarmanv5), at least have the decency to credit it. :roll_eyes:

**Comment by charles-sd** [comment]
> @charles-sd [a8ecbd6](https://github.com/StephanJoubert/home_assistant_solarman/pull/270/commits/a8ecbd6f2632f602bdeb5d379cda611d0813ec43) looks _very_ [familiar](https://github.com/jmccrohan/pysolarmanv5/commit/edeee309191cedb4b16437b66a852276740e6594). If you're going to copy code from [pysolarmanv5](https://github.com/jmccrohan/pysolarmanv5), at least have the decency to credit it. 🙄

:no_mouth:

@jmccrohan, please accept my humble apologies. I had your project noted in a CREDITS file which seems was not part of my commit. Embarrassing to say the least. Posting contents here:

**Thanks to the epic documentation (https://pysolarmanv5.readthedocs.io/) and code (https://github.com/jmccrohan/pysolarmanv5) from the pysolarmanv5 project for information and examples on using the header serial field in this protocol.**

As a side note: Post my quick fixes to eliminate this bug, I am considering a proposal to refactor this project to use the pysolarmanv5 library instead of what is under the hood today. The present protocol implementation is extremely opaque and made chasing down my problem very time consuming. The pysolarmanv5 library is a significantly expanded and mature implementation of the protocol used by this HA custom component.

**Comment by jmccrohan** [comment]
@charles-sd Thanks. No harm done. :smile:

**Comment by charles-sd** [comment]
> @charles-sd When I saw your PR, I thought that it would probably be a good idea to use pysolarmanpv5 in this project 🙂

I also opened Discussion #271. Feel free to support the proposal there. 😃

**Comment by NemesisXB** [comment]
This should be added. I merged it for my own setups. I am managing 3 installls, 2 never had issues, the one has very shoddy network and had multiple glitches in the data per day. I added this and the glitches are gone!

**Comment by PV-Joe** [comment]
How exactly do I update this fix into my 1.4.3 Installation or do I have to wait for the next release?

Thx for your advice.

**Comment by NemesisXB** [comment]
I basically replaced my solarman.py in my custom_components/solarman folder in home assistant with the one from this repo and branch: https://github.com/charles-sd/home_assistant_solarman/tree/fix-gaps-missing-data/custom_components/solarman.

Or wait for the next release as this change has now been merged.

**Comment by PV-Joe** [comment]
> I basically replaced my solarman.py in my custom_components/solarman folder in home assistant with the one from this repo and branch: https://github.com/charles-sd/home_assistant_solarman/tree/fix-gaps-missing-data/custom_components/solarman.
> 
> Or wait for the next release as this change has now been merged.

I did exchange the „solarman.py“ file with the one you suggested. After restarting Home Assistant everything seems to work as before.

I‘m curious if the problem is cured now. 😄

**Pull request merged**
